# Get all characters.

GET http://localhost:9080/simple-rpg/api/buildings

###

# Get single character.

GET http://localhost:9080/simple-rpg/api/buildings/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

###

# Get single character. Not existing, created later.

GET http://localhost:9080/simple-rpg/api/buildings/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Create new character.

PUT http://localhost:9080/simple-rpg/api/buildings/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "name": "Centrum Nanotechnologii B",
  "area": 2320,
  "number": 18,
  "maximumOccupancy": 300,
  "buildingAdministrator": "81e1c2a9-7f57-439b-b53d-6db88b071e4e",
  "organizationalUnit": "5d1da2ae-6a14-4b6d-8b4f-d117867118d4"
}

###


# Create new character. Not existing profession.

PUT http://localhost:9080/simple-rpg/api/buildings/3c6f1eb1-8069-44ab-988f-d7fed2b6fefe
Content-Type: application/json

{
  "name": "Nowe ETI",
  "area": 4320,
  "number": 42,
  "maximumOccupancy": 2000,
  "buildingAdministrator": "81e1c2a9-7f57-439b-b53d-6db88b071e4e",
  "organizationalUnit": "5d1da2ae-6a14-4b6d-8b4f-d117867ffff4"
}

###

# Update character.

PATCH http://localhost:9080/simple-rpg/api/buildings/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
  "maximumOccupancy": 320,
  "number": 41
}

###

# Delete character.

DELETE http://localhost:9080/simple-rpg/api/buildings/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

###

# Get all professions.

GET http://localhost:9080/simple-rpg/api/organizational_units

###

# Get all profession characters.

GET http://localhost:9080/simple-rpg/api/organizational_units/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/buildings

###

# Get all profession characters. Not existing.

GET http://localhost:9080/simple-rpg/api/organizational_units/d8b50a43-ed45-4441-9bcb-5db7782b47f6/buildings

###

# Get all user characters.

GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/buildings

###

# Get all user characters. Empty.

GET http://localhost:9080/simple-rpg/api/users/ed6cfb2a-cad7-47dd-9b56-9d1e3c7a4197/buildings

###

GET http://localhost:9080/simple-rpg/api/users/

###

# Get user

GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e


###

# Get user not existing

GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4f

# Get all user characters. Not existing.

###
GET http://localhost:9080/simple-rpg/api/users/c07cab55-a56f-4d67-b351-175bb7a94b7a/buildings


# Create character portrait.

###
PUT http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< simple-rpg/src/main/resources/pl/edu/pg/eti/kask/rpg/configuration/avatar/sigrid.png
--boundary--

###
GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar

###
DELETE http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/avatar